Update configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,6 +11,25 @@ cmake -H. -B_builds \
     -DCMAKE_INSTALL_PREFIX=_install \
     -DCMAKE_SHARED_LIBRARY_PREFIX_CXX=""
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+LDFLAGS=`"${R_HOME}/bin/R" CMD config LDFLAGS`
+
+cd src
+mkdir build && cd build
+cmake ../libs \
+  -DCMAKE_BUILD_TYPE=Release \
+  -DBUILD_SHARED_LIBS:bool=OFF \
+  -DCMAKE_POSITION_INDEPENDENT_CODE:bool=ON
+${MAKE}
+
+
 cmake --build _builds --target install --config Release
 
 # Linux
